sugar-org/sugar

.containers-sugar.yaml
.github/workflows/main.yaml
.vscode/settings.json
README.md
conda/dev.yaml
containers/tests/group1/compose.yaml
containers/tests/group2/compose.yaml
containers_sugar/__init__.py
containers_sugar/__main__.py
containers_sugar/containers_sugar.py
containers_sugar/sugar.py
poetry.lock
pyproject.toml

this PR aims to add the initial functionalities.
the wait and get-ip will be addressed in a follow up PR.
* ```...```
This PR is a:
About this PR:
```
```

Add initial functionalities

---

.github/workflows/main.yaml
.github/workflows/release.yaml
.releaserc.json

This PR aims to fix the semantic release workflow
* ```...```
This PR is a:
About this PR:
```
```

fix: Fix semantic release workflow

---

.github/workflows/main.yaml
.github/workflows/release.yaml

this PR aims to fix the ci timeout minutes key
* ```...```
This PR is a:
About this PR:
```
```

fix: Fix ci timeout-minutes

---

.releaserc.json
containers_sugar/__init__.py
pyproject.toml

This PR aims to fix the semantic release replace plugin configuration
* ```...```
This PR is a:
About this PR:
```
```

fix: semantic-release replace plugin configuration

---

.releaserc.json

* ```...```
This PR is a:
About this PR:
```
```

fix: Fix quotes used by semantic release replace

---

.github/workflows/release.yaml

This PR aims to fix the semantic release call for dry run mode
* ```...```
This PR is a:
About this PR:
```
```

ci: fix the semantic release call for dry run mode

---

.github/workflows/main.yaml
containers_sugar/sugar.py
tests/test_containers_sugar.py

This PR aims to suppress the traceback from the sh when the target fails
* ```...```
This PR is a:
About this PR:
```
```

fix: Suppress traceback from sh

---

containers_sugar/sugar.py

This PR aims to fix the issue with sh call
* ```...```
This PR is a:
About this PR:
```
```

fix: Fix the sh call in background

---

.github/workflows/main.yaml
containers_sugar/sugar.py

This PR aims to fix the import of the sh lib and add pre-commit run to CI
* ```...```
This PR is a:
About this PR:
```
```

fix: Fix the import of sh lib and add pre-commit run to CI

---

containers_sugar/__main__.py
containers_sugar/sugar.py

This PR aims to fix the access to env-file and improve version sub-command output
* ```...```
This PR is a:
About this PR:
```
```

fix: Fix the access to env-file and improve version sub-command output

---

containers_sugar/sugar.py

This PR aims to add initial implementation for `run` and `exec` sub-commands
* ```...```
This PR is a:
About this PR:
```
```

feat: Add initial implementation for `run` and `exec` sub-command

---

containers_sugar/sugar.py

* ```...```
This PR is a:
About this PR:
```
```

feat: Add extra args and command argument and fix some issues

---

.containers-sugar.yaml
.github/workflows/main.yaml
Makefile
containers_sugar/sugar.py

This PR aims to fix the --extras parameters and improve the CI
* ```...```
This PR is a:
About this PR:
```
```

fix: Fix --extras parameter and improve the CI

---

containers/tests/group1/compose.yaml
containers_sugar/sugar.py

This PR aims to fix the argument `all`
fix #33 
* ```...```
This PR is a:
About this PR:
```
```

fix: Fix the argument `--all`

---

containers_sugar/sugar.py

This PR aims to allow the extras for all the sub-commands
* ```...```
This PR is a:
About this PR:
```
```

fix: Use extras for all sub-commands

---

containers_sugar/sugar.py

fix: Remove --volumes from down command

---

.flake8
.github/workflows/main.yaml
Makefile
README.md
containers_sugar/__main__.py
containers_sugar/sugar.py

This PR aims to improve the usage of the parameters passed to the compose app.
it renames `--extras` to `--options` and improve both `--options` and `--cmd` in order to allow it outside quotes.
```bash
containers-sugar run --group group1 --service service1-1 --options -T --cmd python -c "print('test')"
```
* ```...```
This PR is a:
About this PR:
```
```

refactor: Improve the usage of parameters --cmd and --options (formerly --extras) 

---

Makefile
README.md
containers_sugar/__main__.py
pyproject.toml

Add the kxgr alias to containers-sugar
* ```...```
This PR is a:
About this PR:
```
```

feat: Add the alias kxgr to containers-sugar

---

README.md

Update documentation, including the new commands and a quick explanation about **main** and **ext** profile/plugin.
* ```...```
This PR is a:
About this PR:
```
```

docs: Update documentation with  new commands and a quick explanation about **main** and **ext** profile/plugin

---

containers_sugar/sugar.py

Fix the Ext commands restart and start
* ```...```
This PR is a:
About this PR:
```
```

fix(ext): Fix restart and start ext commands

---

.containers-sugar.yaml
.github/workflows/main.yaml
.github/workflows/release.yaml
Makefile
conda/dev.yaml
containers_sugar/sugar.py
poetry.lock
pyproject.toml
tests/test_containers_sugar.py

* ```...```
This PR is a:
About this PR:
```
```

feat: Add support for compose v2

---

.github/workflows/main.yaml
.github/workflows/release.yaml
conda/dev.yaml
conda/release.yaml
poetry.lock
pyproject.toml

* ```...```
This PR is a:
About this PR:
```
```

fix: Fix distlib installation failure

---

.github/workflows/main.yaml
pyproject.toml

* ```...```
This PR is a:
About this PR:
```
```

feat(deps): Add support for python 3.11 and 3.12

---

src/sugar/sugar.py

Changed KxgrLogs for KxgrErrorType
Solving issue #083
* ```...```
This PR is a:
About this PR:
```
```

bug: changed KxgrLogs for KxgrErrorType

---

.github/workflows/main.yaml
poetry.lock
pyproject.toml
src/sugar/console.py
src/sugar/inspect.py
src/sugar/plugins/base.py
src/sugar/plugins/stats.py

* ```...```
This PR is a:
About this PR:
```
```

fix: Fix initial configuration for stats plot

---

.prettierignore
.prettierrc.yaml
docs/contributing.md

* ```...```
This PR is a:
About this PR:
```
```

docs: Improve the contributing guide

---

.github/workflows/docs.yaml
.github/workflows/main.yaml
.github/workflows/release.yaml
.makim.yaml
.prettierignore
.releaserc.json
conda/dev.yaml
conda/release.yaml
poetry.lock
pyproject.toml
src/sugar/__init__.py
src/sugar/__main__.py
src/sugar/cli.py
src/sugar/console.py
src/sugar/core.py
src/sugar/inspect.py
src/sugar/logs.py
src/sugar/plugins/base.py
src/sugar/plugins/ext.py
src/sugar/plugins/stats.py
tests/test_containers_sugar.py

* ```...```
This PR is a:
About this PR:
```
```

fix: Change rich lower bound pin to >=10.11.0

---

.github/workflows/release.yaml

* ```...```
This PR is a:
About this PR:
```
```

fix: Fix typo in the release workflow

---

.github/workflows/main.yaml
poetry.lock
pyproject.toml
src/sugar/core.py

* ```...```
This PR is a:
About this PR:
```
```

fix: Isolate dependencies for stats plot

---

.makim.yaml
src/sugar/cli.py
src/sugar/plugins/base.py

This PR removes unnecessary flags for the commands and add docstrings that are used in the help menu.
* ```...```
This PR is a:
About this PR:
```
```

fix: Improve the usage of flags for the CLI

---

.makim.yaml
.sugar.yaml
poetry.lock
pyproject.toml
src/sugar/cli.py
src/sugar/plugins/base.py
tests/containers/.services.sugar.yaml

This PR aims to add new docker compose commands: attach, cp, ls, scale, wait, and watch.
It will be added as in experimental mode, because there is not test yet for them, they need specific test approach.
* ```...```
This PR is a:
About this PR:
```
```

feat(experimental): Add new docker compose commands: attach, cp, ls, scale, wait, watch

---

.editorconfig
.env
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/main.yaml
.github/workflows/release.yaml
.makim.yaml
.pre-commit-config.yaml
.sugar.yaml
CODE_OF_CONDUCT.md
README.md
conda/dev.yaml
conda/release.yaml
docs/contributing.md
docs/images/site.webmanifest
docs/index.md
docs/installation.md
poetry.lock
pyproject.toml
src/sugar/__main__.py
src/sugar/cli.py
src/sugar/console.py
src/sugar/core.py
src/sugar/logs.py
src/sugar/plugins/base.py
src/sugar/plugins/ext.py
src/sugar/plugins/stats.py
tests/containers/.services.sugar.yaml
tests/containers/group1/compose.yaml
tests/containers/group2/compose.yaml

This PR aims to:
* change jinja2 template tag from `{{ }}` to `${{ }}` this avoid issues with linters
* update package paginate
* add proper configuration for mypy and fix type annotation issues
* rename usage of prefix `KXGR` to `SUGAR`
* add prettier for auto-formatting tool in the pre-commit hook
* ```...```
This PR is a:
About this PR:
```
```

fix: fix the jinja2 template in the config file

---

.github/workflows/main.yaml
.makim.yaml
.pre-commit-config.yaml
.sugar.yaml
poetry.lock
pyproject.toml
src/sugar/__init__.py
src/sugar/__main__.py
src/sugar/cli.py
src/sugar/core.py
src/sugar/docs.py
src/sugar/extensions/base.py
src/sugar/extensions/compose.py
src/sugar/extensions/compose_ext.py
src/sugar/extensions/stats.py
src/sugar/logs.py
tests/containers/.services.sugar.yaml
tests/test_containers_sugar.py
tests/test_docs.py

- `...`
This PR is a:
About this PR:
complexity.
```
```

fix: Refactor and fix  sugar classes and CLI

---

.makim.yaml
poetry.lock
pyproject.toml
src/sugar/cli.py
src/sugar/extensions/base.py
src/sugar/utils.py
tests/containers/.hooks.sugar.yaml

- `...`
This PR is a:
About this PR:
complexity.
```
```

feat: Add support for hooks

---

src/sugar/schema.json

- `...`
This PR is a:
About this PR:
complexity.
```
```

fix: Fix specification of required attributes in schema.json

---

.github/workflows/main.yaml
.pre-commit-config.yaml
poetry.lock

- `...`
This PR is a:
About this PR:
complexity.
```
```

chore(support): Add support for Python 3.13

---

docs/index.md

This PR fixes the documentation rendering issue in the documentation github page for Sugar project
Solves #139
```sh
mkdocs serve
```
This PR is a:
About this PR:
complexity.
```
```

fix(docs): resolve 'env' undefined error in documentation site

---

README.md

fix(docs): Update README.md according to schema.json

---

src/sugar/console.py

Fix bug in get_terminal_size() function where incorrect variable is assigned in error handling
Solves #163 
This PR is a:
About this PR:
complexity.
Before:
After:
```
```

fixed get_terminal_size()

---

.github/workflows/stale.yaml

- `...`
This PR is a:
About this PR:
complexity.
```
```

chore(ci): Add ci workflow for closing prs

---

.github/workflows/stale.yaml

- `...`
This PR is a:
About this PR:
complexity.
```
```

chore(ci): Increase timelines for stale workflow

---

.makim.yaml
docs/swarm.md
src/sugar/core.py
src/sugar/extensions/base.py
src/sugar/extensions/podman_ext.py
src/sugar/extensions/swarm.py
src/sugar/utils.py
tests/containers/.unittest-swarm.sugar.yaml
tests/test_podman_ext.py
tests/test_swarm.py

- `...`
This PR is a:
About this PR:
complexity.
```
```

refactor: Change the CLI layout for swarm

---

.makim.yaml
docs/changelog.md
docs/podman-ext.md
docs/swarm.md
src/sugar/cli.py
src/sugar/extensions/compose.py
src/sugar/extensions/podman_ext.py
src/sugar/extensions/swarm.py

- `...`
This PR is a:
About this PR:
complexity.
```
```

feat: Replace --options by <SPACE>--<SPACE>
